### PR TITLE
feat: update features on homepage

### PR DESCRIPTION
**Pull request by samajammin**
Working with the design team on building illustrations for these features, so wanted to quickly update these

## Before

Image 2023-11-29 at 13 49 33

## After

Image 2023-11-29 at 13 46 29

### CODE REVIEW

**Comment by samajammin** [comment]
@ctrlc03 tagging you for review - I believe you originally created these features.

My main reasoning is that MACI optimizes for security > ease of use. Obviously we want both but when it comes to tradeoffs, I think it's clear the system has been designed to ensure security. I suspect there's many other voting systems which are easier to use 😄

**Review by ctrlc03 — CHANGES_REQUESTED** [review]
After the first read of the first section, it feels like we are saying that these security properties come solely from the project using the Ethereum blockchain, whereas certain properties listed here do come from the protocol itself. Not sure if we can reword this? for instance, while votes are recorded on chain, the processing is done offchain, so technically the non-censurability comes from other parts of the code, not the blockchain itself.

The rest looks great, thanks for improving this section

**Comment by samajammin** [comment]
> After the first read of the first section, it feels like we are saying that these security properties come solely from the project using the Ethereum blockchain, whereas certain properties listed here do come from the protocol itself. Not sure if we can reword this? for instance, while votes are recorded on chain, the processing is done offchain, so technically the non-censurability comes from other parts of the code, not the blockchain itself.
> 
> The rest looks great, thanks for improving this section

@ctrlc03 updated slightly to mention the smart contracts - how's that looks for now? Didn't mention the ZK stuff because that's highlighted in the other feature.

**Review by ctrlc03 — APPROVED** [review]
Thanks for improving this section, LGTM

**Review by ctrlc03 — DISMISSED** [review]

**Review by ctrlc03 — APPROVED** [review]

**Pull request merged**
