### PR TITLE
chore(deps): update project dependencies and remove redundant ones

### PR DESCRIPTION
**Pull request by ctrlc03**
# Description

Remove redundant dependencies, run `npm audit` and upgrade what is possible. 

## Related issue(s)

Depends on #961 being merged first

re: #793 

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://github.com/privacy-scaling-explorations/maci/blob/dev/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/maci/blob/dev/CODE_OF_CONDUCT.md).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Review by 0xmad — COMMENTED** [review]
@ctrlc03 thanks, what do you think about installing renovation or dependabot to support automation for dependency management?
And what's about the dev deps updates?

**Comment by ctrlc03** [comment]
> @ctrlc03 thanks, what do you think about installing renovation or dependabot to support automation for dependency management? And what's about the dev deps updates?

We have dependabot though not sure how it's setup nor am familiar with it, wanna check its config? 

what about the dev deps updates?

**Comment by 0xmad** [comment]
@ctrlc03 there are some dev deps which have new versions but in the project they have the old ones (for instance, chai)

**Comment by ctrlc03** [comment]
> @ctrlc03 there are some dev deps which have new versions but in the project they have the old ones (for instance, chai). Yes, I can take a look at dependabot.

oh right, let me update those too

**Review by 0xmad — APPROVED** [review]
@ctrlc03 thanks! Let's merge it and other updates will be done via dependabot.

**Pull request merged**
