### PR TITLE
docs: replacement of idle links

### PR DESCRIPTION
**Pull request by braveocheretovych**
hey. replacement of idle links

# Description

## Confirmation

- [ ] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [ ] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [ ] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Review by ctrlc03 — COMMENTED** [review]
please can you fix your commit message? it should not have capital letters. the commitilint CI job shows you what to fix. thank you

**Comment by braveocheretovych** [comment]
done

**Comment by braveocheretovych** [comment]
I'm a beginner and I don't fully understand what I still need to do. Can delete this request pool and create a new one

**Comment by ctrlc03** [comment]
> I'm a beginner and I don't fully understand what I still need to do. Can delete this request pool and create a new one

Yes that would work too. Please make sure the commit is `docs: replacement of idle links` and we'll then merge it - thanks

**Pull request closed without merging**
