### PR TITLE
fix: fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by ctrlc03 — APPROVED** [review]
Thank you!

**Review by ctrlc03 — CHANGES_REQUESTED** [review]
Could you please run prettier? CI complains about `spec.md` 🙏 thanks

**Comment by rex4539** [comment]
Not sure why it's failing. Looks fine when I run it locally on my branch.

```
/Users/rex/rex4539-maci/website/versioned_docs/version-v1.x on branch typos rex@MacBook-Pro% npx prettier -c .        
Checking formatting...
All matched files use Prettier code style!
```

**Comment by ctrlc03** [comment]
> Not sure why it's failing. Looks fine when I run it locally on my branch.
> 
> ```
> /Users/rex/rex4539-maci/website/versioned_docs/version-v1.x on branch typos rex@MacBook-Pro% npx prettier -c .        
> Checking formatting...
> All matched files use Prettier code style!
> ```

mm not sure why 🤔  have you run `pnpm prettier:fix` and commited the changes after that?

**Comment by rex4539** [comment]
Should be ok now.

**Review by ctrlc03 — APPROVED** [review]

**Pull request merged**
