### PR TITLE
refactor(contracts): remove maxValues from Maci.deployPoll() and instead calculate

### LINKED ISSUE #1066: Simplify circuit parameter configuration by always deriving MaxValues and BatchSizes from TreeDepths
# Prerequisites

Please answer the following question for yourself before submitting a feature request.

- [x] I checked to make sure that this request has not already been filed

# Motivation
Currently, to use these circuits from the ceremony, 

tallyVotes_6-2-3
processMessage_6-8-2-3

applications (e.g clr.fund) have to pass the derivable data 
1) MaxValues to maci.deployPoll()
2) messageBatchSize to VKRegistry

Change request:
1) remove MaxValues from deployPoll() interface and let MACI calculate it
2) replace messageBatchSize with messageTreeSubDepth in VKRegistry and MessageProcessor

The intent is to minimize inconsistency and error in applications passing the wrong messageBatchSize or MaxValues to MACI.

```
  function deployPoll(
    uint256 _duration,
    MaxValues memory _maxValues,
    TreeDepths memory _treeDepths,
    PubKey memory _coordinatorPubKey,
    address _verifier,
    address _vkRegistry,
    bool useSubsidy
  ) 

  function setVerifyingKeys(
    uint256 _stateTreeDepth,
    uint256 _intStateTreeDepth,
    uint256 _messageTreeDepth,
    uint256 _voteOptionTreeDepth,
    uint256 _messageBatchSize,
    VerifyingKey calldata _processVk,
    VerifyingKey calldata _tallyVk
  )
```

# Details

Please describe your feature request in detail.

Make sure that you have reviewed [MACI's Contributor Guidelines](https://maci.pse.dev/docs/contributing)

### PR DESCRIPTION
**Pull request by ctrlc03**
# Description

Simplify logic and save gas by computing maxValues and batchSizes within MACI vs passing as parameter to deployPoll.
Also cache variables fetched from the poll contract, and pass around the various functions inside MessageProcessor.

Benefits: 

* Reduction of gas consumption to deploy Poll and various contracts.
* large gas saving in the `processMessages` function

## Related issue(s)

fix #1066

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Review by 0xmad — APPROVED** [review]
@ctrlc03 thanks, just one question about slither warnings: does it make sense to fix them?

**Comment by ctrlc03** [comment]
> @ctrlc03 thanks, just one question about slither warnings: does it make sense to fix them?

I'm not sure tbh. Maybe in one PR we can try and remove all `_` from params, though I thought in solidity it was normal to have them 🤔

**Comment by 0xmad** [comment]
> > @ctrlc03 thanks, just one question about slither warnings: does it make sense to fix them?
> 
> I'm not sure tbh. Maybe in one PR we can try and remove all `_` from params, though I thought in solidity it was normal to have them 🤔

So that why I asked. This one is a low level warning so maybe it makes sense to revise solidity code style and agree where to use underscore. After that we can just configure slither to get rid of the noise about these issues.

**Comment by 0xmad** [comment]
https://docs.soliditylang.org/en/v0.4.25/style-guide.html#naming-conventions
This link is recommended by slither warning.

**Comment by samajammin** [comment]
> https://docs.soliditylang.org/en/v0.4.25/style-guide.html#naming-conventions This link is recommended by slither warning.

So looks like they generally don't recommend leading with underscores? I'm happy to adopt what the Solidity docs recommend.

**Pull request merged**
