### PR TITLE
docs: refactor documentation website

### LINKED ISSUE #1342: re-organize documentation entries to be more digestible
It was brought up that MACI's documentation can be too much to go through, and a re-organization could help slim down the content and provide a clearer path for interested users/developers

### PR DESCRIPTION
**Pull request by ctrlc03**
# Description

Organize in folders various entries to provide better readability. 

## Related Issue(s)

fix #1342 

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Review by kittybest — COMMENTED** [review]
do you think we could also add `_category_.json` to solidity doc and type doc?
else we might put some simple description to the index page, they look so empty now 🤔
.
another question, would you think the `quick start` and `guides` part should be put together? since for me, as a new user who just wanna try to run it first, would see the `installation` page first then the `deployment` page.

**Review by 0xmad — APPROVED** [review]
@ctrlc03 thanks!

**Comment by ctrlc03** [comment]
> do you think we could also add `_category_.json` to solidity doc and type doc?

Yes that's very needed, was thinking to do that in another PR if that's ok 

> another question, would you think the quick start and guides part should be put together? 

I see, yea that makes sense. And maybe move the integration doc to the developer specific resources?

**Comment by kittybest** [comment]
> > do you think we could also add `_category_.json` to solidity doc and type doc?
> 
> Yes that's very needed, was thinking to do that in another PR if that's ok

Yes!

> > another question, would you think the quick start and guides part should be put together?
> 
> I see, yea that makes sense. And maybe move the integration doc to the developer specific resources?

I think the current structure is good!
But where are the solidity-docs and typedoc?

**Comment by ctrlc03** [comment]
> > > do you think we could also add `_category_.json` to solidity doc and type doc?
> > 
> > 
> > Yes that's very needed, was thinking to do that in another PR if that's ok
> 
> Yes!
> 
> > > another question, would you think the quick start and guides part should be put together?
> > 
> > 
> > I see, yea that makes sense. And maybe move the integration doc to the developer specific resources?
> 
> I think the current structure is good! But where are the solidity-docs and typedoc?

they are inside developers-resources/ inside typescript there's the typedoc + cli docs and inside smart-contracts there's solidity docs

**Review by kittybest — APPROVED** [review]

**Pull request merged**
