### PR TITLE
Check lint in CI

### PR DESCRIPTION
**Pull request by gurrpi**
This is a naive implementation that checks if the build and lint passes.

### CODE REVIEW

**Comment by corydickson** [comment]
@gurrpi Is this PR still relevant? It looks like we have checks already for v1

**Comment by gurrpi** [comment]
> @gurrpi Is this PR still relevant? It looks like we have checks already for v1

This PR introduces check lint errors. I will change the PR name to make it more clear and file an issue for current lint error.

**Comment by samajammin** [comment]
@gurrpi is this still something we want to merge?

**Comment by gurrpi** [comment]
> @gurrpi is this still something we want to merge?

Closing this due to its age and existing lint errors in our codebase. For lint checks in CI, a new, updated PR would be more appropriate.

**Pull request closed without merging**
