### PR TITLE
docs(diagram): add contract architecture diagram

### LINKED ISSUE #1202: Create smart contract architecture diagrams
# Motivation

As a user or developer looking to learn more about MACI, I'd love to see visual resources to understand the high-level architecture of the MACI system

# Details

Add charts to https://maci.pse.dev/docs/contracts/

Similar to 
image

But include MACI & Poll contracts like
image

### PR DESCRIPTION
**Pull request by wiasliaw**
# Description

close #1202.

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Review by ctrlc03 — COMMENTED** [review]
Would you like to add diagrams for all other contracts interactions? Like the Poll contract, Tally, MessageProcessor, and how they fit within the architecture?

**Review by kittybest — COMMENTED** [review]
since `genProof` is also done by the coordinator, maybe the arrow should look like `decrypt`? (start from the coordinator)

**Comment by kittybest** [comment]
IMG_0655
Thinking about something like this? How do you think?

**Comment by kittybest** [comment]
If adding more contracts on this diagram to make it clearer (based on ctrl03’s comment)
5983784D-64DE-46A3-9B49-5BE10FDFC502

looks a little bit messy, need to be arranged properly

**Comment by kittybest** [comment]
@wiasliaw do you have time to revise this PR? or could you give us the original diagram file that we could modify? thanks a lot!

**Comment by wiasliaw** [comment]
@kittybest and @ctrlc03 
I had updated the new svg. And here is the edit link of the source file.

https://www.tldraw.com/r/cdVS7WgJZpKs21TXoiWsd?v=-1274,-1268,4897,3431&p=FUBKca68HYLYZLHOIybOd

**Review by kittybest — APPROVED** [review]
thanks!

**Comment by kittybest** [comment]
@wiasliaw could you fix the conflicts? Thanks a lot!

**Comment by wiasliaw** [comment]
@kittybest NP! Done!

**Review by ctrlc03 — APPROVED** [review]
Very neat diagram, thanks very much

**Pull request merged**
