### PR TITLE
docs(documentation): added getting started with maci article to docs

### PR DESCRIPTION
**Pull request by BenBarahona**
# Description

Added link to article about how to setup and run MACI aimed for developers.

## Additional Notes

None

## Related issue(s)

None

## Confirmation

- [X] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [X] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [X] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Comment by ctrlc03** [comment]
Hi @BenBarahona thanks for this, could you please amend your commit to follow guidelines? there should not be capitals: https://github.com/privacy-scaling-explorations/maci/actions/runs/12267517123/job/34227754808

**Comment by BenBarahona** [comment]
> Hi @BenBarahona thanks for this, could you please amend your commit to follow guidelines? there should not be capitals: https://github.com/privacy-scaling-explorations/maci/actions/runs/12267517123/job/34227754808

I think it should be ok now!

**Comment by ctrlc03** [comment]
> > Hi @BenBarahona thanks for this, could you please amend your commit to follow guidelines? there should not be capitals: https://github.com/privacy-scaling-explorations/maci/actions/runs/12267517123/job/34227754808
> 
> I think it should be ok now!

So we don't use merge but rebase, could you please rebase to dev, then squash your commits into one (`git reset $(git merge-base dev $(git rev-parse --abbrev-ref HEAD))`) and force push one commit? Thanks so much

**Review by crisgarner — APPROVED** [review]

**Comment by crisgarner** [comment]
Thanks!

**Comment by BenBarahona** [comment]
> > > Hi @BenBarahona thanks for this, could you please amend your commit to follow guidelines? there should not be capitals: https://github.com/privacy-scaling-explorations/maci/actions/runs/12267517123/job/34227754808
> > 
> > 
> > I think it should be ok now!
> 
> So we don't use merge but rebase, could you please rebase to dev, then squash your commits into one (`git reset $(git merge-base dev $(git rev-parse --abbrev-ref HEAD))`) and force push one commit? Thanks so much

Got it!  Thanks for the help there

**Pull request merged**
