### PR TITLE
chore: fix 404 status URL

### PR DESCRIPTION
**Pull request by braveocheretovych**
fixing broken links

Description
Add missing exports for contracts package

Additional Notes
N/A

Related issue(s)
Related to https://github.com/privacy-scaling-explorations/maci-platform/issues/433

Confirmation
 I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
 I have read and understand MACI's https://github.com/privacy-scaling-explorations/maci/discussions/847.
 I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Review by ctrlc03 — CHANGES_REQUESTED** [review]
Thanks, please ensure that the commit message respects these guidelines https://maci.pse.dev/docs/contributing/#commits-rules

**Comment by ctrlc03** [comment]
@braveocheretovych checking if you saw my comment regarding the CI failure, your commit message would need to be amended before this is merged. more info: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by ctrlc03** [comment]
@braveocheretovych i saw you changed the title of the PR, however you will need to change the actual commit message. I sent a link on how that works and also there's more info here: https://maci.pse.dev/docs/contributing/#pull-requests

**Comment by braveocheretovych** [comment]
I'm just new to this topic. I made a commit through editing on Github without a terminal, I can't figure out how to fix this problem

**Comment by ctrlc03** [comment]
@braveocheretovych you could close this PR and open a new one, but make sure your commit message is "chore: fix 404 status URL"

**Comment by braveocheretovych** [comment]
ok

**Pull request closed without merging**
