### PR TITLE
chore: use relative links

### PR DESCRIPTION
**Pull request by enjoyooor**
# Description

I believe using relative links is cleaner in case repo/org name changes in the future, small cleanup!

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Comment by ctrlc03** [comment]
> How do I re-run the netlify build? I updated the PR but looks like the build wasn't retriggered?

First of all, thanks for your PR. Looks like there's some broken links which cause the docusaurus build to fail, hence why you don't see a netlify deployment. Could you please run the website build locally and fix the broken links that prevent it from building?

**Comment by ctrlc03** [comment]
> @ctrlc03 looks like there;s some unrelated test failures here?
> 
> > Caused by: Error: the tx doesn't have the correct nonce. account has nonce of: 61 tx has nonce of: 60
> 
> Can you please help take a look fren?

That is fine now, however there is still a build error in the website due to broken links. Have a look at this script: https://github.com/privacy-scaling-explorations/maci/blob/dev/.github/scripts/website.sh - this is how the website is built on netlify. If you follow the same steps, you'll see that the build process fails locally too. 

This is the error log:

```bash
  Exhaustive list of all broken links found:
  - Broken link on source page path = /blog:
     -> linking to circuits/circom/tallyVotes.circom (resolved as: /circuits/circom/tallyVotes.circom)
  - Broken link on source page path = /blog/maci-v1-2-0-release:
     -> linking to docs/trusted-setup (resolved as: /blog/docs/trusted-setup)
     -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/circuits/circom/tallyVotes.circom)
  - Broken link on source page path = /blog/tags/audit:
     -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
     -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
  - Broken link on source page path = /blog/tags/documentation:
     -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
     -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
  - Broken link on source page path = /blog/tags/release:
     -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
     -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
  - Broken link on source page path = /blog/tags/security:
     -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
     -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
  - Broken link on source page path = /docs/circuits:
     -> linking to circuits/circom/processMessages.circom (resolved as: /docs/circuits/circom/processMessages.circom)
     -> linking to circuits/circom/tallyVotes.circom (resolved as: /docs/circuits/circom/tallyVotes.circom)
     -> linking to circuits/circom/subsidy.circom (resolved as: /docs/circuits/circom/subsidy.circom)
  - Broken link on source page path = /docs/integrating:
     -> linking to contracts/contracts/Tally.sol (resolved as: /docs/contracts/contracts/Tally.sol)
     -> linking to contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol)
     -> linking to contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol)
  - Broken link on source page path = /docs/key-change:
     -> linking to core/ts/__tests__/ (resolved as: /docs/core/ts/__tests__/)
     -> linking to cli/tests/ (resolved as: /docs/cli/tests/)
  - Broken link on source page path = /docs/poll-types:
     -> linking to contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol)
  - Broken link on source page path = /docs/testing:
     -> linking to integrationTests/scripts/download_zkeys.sh (resolved as: /docs/integrationTests/scripts/download_zkeys.sh)
  - Broken link on source page path = /docs/testing-in-detail:
     -> linking to circuits/ts/__tests__/CeremonyParams.test.ts (resolved as: /docs/circuits/ts/__tests__/CeremonyParams.test.ts)
     -> linking to docs/trusted-setup (resolved as: /docs/docs/trusted-setup)
     -> linking to core/ts/__tests__/e2e.test.ts (resolved as: /docs/core/ts/__tests__/e2e.test.ts)
     -> linking to cli/testScript.sh (resolved as: /docs/cli/testScript.sh)
  - Broken link on source page path = /docs/topup:
     -> linking to contracts/contracts/Poll.sol (resolved as: /docs/contracts/contracts/Poll.sol)
  - Broken link on source page path = /docs/typedoc/core/:
     -> linking to contracts/tests/MACI.test.ts (resolved as: /docs/typedoc/core/contracts/tests/MACI.test.ts)
     -> linking to contracts/ts/genMaciState.ts (resolved as: /docs/typedoc/core/contracts/ts/genMaciState.ts)
  - Broken link on source page path = /docs/versioning:
     -> linking to .github/workflows/release.yml (resolved as: /docs/.github/workflows/release.yml)
  - Broken link on source page path = /docs/workflow:
     -> linking to contracts/contracts/gatekeepers/SignUpGatekeeper.sol (resolved as: /docs/contracts/contracts/gatekeepers/SignUpGatekeeper.sol)
```

**Comment by ctrlc03** [comment]
> > > @ctrlc03 looks like there;s some unrelated test failures here?
> > > > Caused by: Error: the tx doesn't have the correct nonce. account has nonce of: 61 tx has nonce of: 60
> > > 
> > > 
> > > Can you please help take a look fren?
> > 
> > 
> > That is fine now, however there is still a build error in the website due to broken links. Have a look at this script: https://github.com/privacy-scaling-explorations/maci/blob/dev/.github/scripts/website.sh - this is how the website is built on netlify. If you follow the same steps, you'll see that the build process fails locally too.
> > This is the error log:
> > ```shell
> >   Exhaustive list of all broken links found:
> >   - Broken link on source page path = /blog:
> >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /circuits/circom/tallyVotes.circom)
> >   - Broken link on source page path = /blog/maci-v1-2-0-release:
> >      -> linking to docs/trusted-setup (resolved as: /blog/docs/trusted-setup)
> >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/circuits/circom/tallyVotes.circom)
> >   - Broken link on source page path = /blog/tags/audit:
> >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> >   - Broken link on source page path = /blog/tags/documentation:
> >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> >   - Broken link on source page path = /blog/tags/release:
> >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> >   - Broken link on source page path = /blog/tags/security:
> >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> >   - Broken link on source page path = /docs/circuits:
> >      -> linking to circuits/circom/processMessages.circom (resolved as: /docs/circuits/circom/processMessages.circom)
> >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /docs/circuits/circom/tallyVotes.circom)
> >      -> linking to circuits/circom/subsidy.circom (resolved as: /docs/circuits/circom/subsidy.circom)
> >   - Broken link on source page path = /docs/integrating:
> >      -> linking to contracts/contracts/Tally.sol (resolved as: /docs/contracts/contracts/Tally.sol)
> >      -> linking to contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol)
> >      -> linking to contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol)
> >   - Broken link on source page path = /docs/key-change:
> >      -> linking to core/ts/__tests__/ (resolved as: /docs/core/ts/__tests__/)
> >      -> linking to cli/tests/ (resolved as: /docs/cli/tests/)
> >   - Broken link on source page path = /docs/poll-types:
> >      -> linking to contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol)
> >   - Broken link on source page path = /docs/testing:
> >      -> linking to integrationTests/scripts/download_zkeys.sh (resolved as: /docs/integrationTests/scripts/download_zkeys.sh)
> >   - Broken link on source page path = /docs/testing-in-detail:
> >      -> linking to circuits/ts/__tests__/CeremonyParams.test.ts (resolved as: /docs/circuits/ts/__tests__/CeremonyParams.test.ts)
> >      -> linking to docs/trusted-setup (resolved as: /docs/docs/trusted-setup)
> >      -> linking to core/ts/__tests__/e2e.test.ts (resolved as: /docs/core/ts/__tests__/e2e.test.ts)
> >      -> linking to cli/testScript.sh (resolved as: /docs/cli/testScript.sh)
> >   - Broken link on source page path = /docs/topup:
> >      -> linking to contracts/contracts/Poll.sol (resolved as: /docs/contracts/contracts/Poll.sol)
> >   - Broken link on source page path = /docs/typedoc/core/:
> >      -> linking to contracts/tests/MACI.test.ts (resolved as: /docs/typedoc/core/contracts/tests/MACI.test.ts)
> >      -> linking to contracts/ts/genMaciState.ts (resolved as: /docs/typedoc/core/contracts/ts/genMaciState.ts)
> >   - Broken link on source page path = /docs/versioning:
> >      -> linking to .github/workflows/release.yml (resolved as: /docs/.github/workflows/release.yml)
> >   - Broken link on source page path = /docs/workflow:
> >      -> linking to contracts/contracts/gatekeepers/SignUpGatekeeper.sol (resolved as: /docs/contracts/contracts/gatekeepers/SignUpGatekeeper.sol)
> > ```
> 
> I didn't encounter this build error. I think just need to be rebased?

I checked out the PR branch which was up to date, and while building the website (`cd website && pnpm build`) I got this error. Did you run the website build command?

**Comment by kittybest** [comment]
> > > > @ctrlc03 looks like there;s some unrelated test failures here?
> > > > > Caused by: Error: the tx doesn't have the correct nonce. account has nonce of: 61 tx has nonce of: 60
> > > > 
> > > > 
> > > > Can you please help take a look fren?
> > > 
> > > 
> > > That is fine now, however there is still a build error in the website due to broken links. Have a look at this script: https://github.com/privacy-scaling-explorations/maci/blob/dev/.github/scripts/website.sh - this is how the website is built on netlify. If you follow the same steps, you'll see that the build process fails locally too.
> > > This is the error log:
> > > ```shell
> > >   Exhaustive list of all broken links found:
> > >   - Broken link on source page path = /blog:
> > >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /circuits/circom/tallyVotes.circom)
> > >   - Broken link on source page path = /blog/maci-v1-2-0-release:
> > >      -> linking to docs/trusted-setup (resolved as: /blog/docs/trusted-setup)
> > >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/circuits/circom/tallyVotes.circom)
> > >   - Broken link on source page path = /blog/tags/audit:
> > >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> > >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> > >   - Broken link on source page path = /blog/tags/documentation:
> > >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> > >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> > >   - Broken link on source page path = /blog/tags/release:
> > >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> > >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> > >   - Broken link on source page path = /blog/tags/security:
> > >      -> linking to docs/trusted-setup (resolved as: /blog/tags/docs/trusted-setup)
> > >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /blog/tags/circuits/circom/tallyVotes.circom)
> > >   - Broken link on source page path = /docs/circuits:
> > >      -> linking to circuits/circom/processMessages.circom (resolved as: /docs/circuits/circom/processMessages.circom)
> > >      -> linking to circuits/circom/tallyVotes.circom (resolved as: /docs/circuits/circom/tallyVotes.circom)
> > >      -> linking to circuits/circom/subsidy.circom (resolved as: /docs/circuits/circom/subsidy.circom)
> > >   - Broken link on source page path = /docs/integrating:
> > >      -> linking to contracts/contracts/Tally.sol (resolved as: /docs/contracts/contracts/Tally.sol)
> > >      -> linking to contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol)
> > >      -> linking to contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol)
> > >   - Broken link on source page path = /docs/key-change:
> > >      -> linking to core/ts/__tests__/ (resolved as: /docs/core/ts/__tests__/)
> > >      -> linking to cli/tests/ (resolved as: /docs/cli/tests/)
> > >   - Broken link on source page path = /docs/poll-types:
> > >      -> linking to contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol (resolved as: /docs/contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol)
> > >   - Broken link on source page path = /docs/testing:
> > >      -> linking to integrationTests/scripts/download_zkeys.sh (resolved as: /docs/integrationTests/scripts/download_zkeys.sh)
> > >   - Broken link on source page path = /docs/testing-in-detail:
> > >      -> linking to circuits/ts/__tests__/CeremonyParams.test.ts (resolved as: /docs/circuits/ts/__tests__/CeremonyParams.test.ts)
> > >      -> linking to docs/trusted-setup (resolved as: /docs/docs/trusted-setup)
> > >      -> linking to core/ts/__tests__/e2e.test.ts (resolved as: /docs/core/ts/__tests__/e2e.test.ts)
> > >      -> linking to cli/testScript.sh (resolved as: /docs/cli/testScript.sh)
> > >   - Broken link on source page path = /docs/topup:
> > >      -> linking to contracts/contracts/Poll.sol (resolved as: /docs/contracts/contracts/Poll.sol)
> > >   - Broken link on source page path = /docs/typedoc/core/:
> > >      -> linking to contracts/tests/MACI.test.ts (resolved as: /docs/typedoc/core/contracts/tests/MACI.test.ts)
> > >      -> linking to contracts/ts/genMaciState.ts (resolved as: /docs/typedoc/core/contracts/ts/genMaciState.ts)
> > >   - Broken link on source page path = /docs/versioning:
> > >      -> linking to .github/workflows/release.yml (resolved as: /docs/.github/workflows/release.yml)
> > >   - Broken link on source page path = /docs/workflow:
> > >      -> linking to contracts/contracts/gatekeepers/SignUpGatekeeper.sol (resolved as: /docs/contracts/contracts/gatekeepers/SignUpGatekeeper.sol)
> > > ```
> > 
> > 
> > I didn't encounter this build error. I think just need to be rebased?
> 
> I checked out the PR branch which was up to date, and while building the website (`cd website && pnpm build`) I got this error. Did you run the website build command?

just re-run it and got the error now 😨 seems like the relative link to github doesn't work

**Comment by ctrlc03** [comment]
hey @enjoyooor just a nudge on this, have you managed to fix the website build errors?

**Comment by ctrlc03** [comment]
> Hey oops sorry, will take a look at this soon!

Hi @enjoyooor any updates on this? seems like it might be possible to have relative links to the monorepo individual files?

**Comment by ctrlc03** [comment]
Hi @enjoyooor - due to inactivity on this PR since April, we will be closing it for now, though feel free to re-open if and when you get a chance to work on it. We appreciate your interest in contributing to MACI and look forward to your future contributions!

**Pull request closed without merging**
