### PR TITLE
fix(cli) - fix incosistencies on return codes

### PR DESCRIPTION
**Pull request by ctrlc03**

### CODE REVIEW

**Comment by baumstern** [comment]
[Given that the calling functions don't check the return codes](https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/index.ts#L203-L243), standardizing them might not add value. For a cleaner approach, I suggest simply using return without any values.

**Comment by baumstern** [comment]
Noticed that e2e integration test failed. Just trigerred to re-run..

**Comment by ctrlc03** [comment]
> [Given that the calling functions don't check the return codes](https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/index.ts#L203-L243), standardizing them might not add value. For a cleaner approach, I suggest simply using return without any values.

yea fair point, I did think that too at first but refrained from changing too much.. if we both agree though I'll just remove the return code everywhere

**Review by baumstern — APPROVED** [review]
LGTM

**Pull request merged**
