### PR TITLE
fix(publish): ensure we publish the correct files

### PR DESCRIPTION
**Pull request by ctrlc03**
# Description

Ensure we publish the correct files by setting the correct paths inside package.json

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://github.com/privacy-scaling-explorations/maci/blob/dev/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/maci/blob/dev/CODE_OF_CONDUCT.md).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Comment by ctrlc03** [comment]
> @ctrlc03 thanks, just one question: do we need different files like license, changelog, readme for npm packages?

yea think that would be good, I'll explicitly add them to files

**Comment by ctrlc03** [comment]
> > @ctrlc03 thanks, just one question: do we need different files like license, changelog, readme for npm packages?
> 
> yea think that would be good, I'll explicitly add them to files

@0xmad seems like LICENSE gets added automatically from project root https://www.npmjs.com/package/maci-cli/v/0.0.0-ci.390bdc3?activeTab=code

**Comment by 0xmad** [comment]
> > > @ctrlc03 thanks, just one question: do we need different files like license, changelog, readme for npm packages?
> > 
> > 
> > yea think that would be good, I'll explicitly add them to files
> 
> @0xmad seems like LICENSE gets added automatically from project root https://www.npmjs.com/package/maci-cli/v/0.0.0-ci.390bdc3?activeTab=code

Ok, let's merge it then.

**Comment by ctrlc03** [comment]
> > > > @ctrlc03 thanks, just one question: do we need different files like license, changelog, readme for npm packages?
> > > 
> > > 
> > > yea think that would be good, I'll explicitly add them to files
> > 
> > 
> > @0xmad seems like LICENSE gets added automatically from project root https://www.npmjs.com/package/maci-cli/v/0.0.0-ci.390bdc3?activeTab=code
> 
> Ok, let's merge it then.

I'll add changelog too, can't hurt having it

**Pull request merged**
