### PR TITLE
docs: fix word repetition

### PR DESCRIPTION
**Pull request by neel-ds**
# Description
There is a section describing what the maci is about. In the content of the answer, there is a single line (#L3) with word repetition. The specific line is _"This ensures the correct the correct execution of votes"_. This PR removes the word repetition and ensures clarity of the content. 

## Related issue(s)
This PR resolves the raised issue #1140 

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Review by ctrlc03 — CHANGES_REQUESTED** [review]
Thanks for this! Just one thing, it seems like there's a duplicate commit, would be able to sort it out locally on your branch and push only one commit? thank you

**Review by kittybest — APPROVED** [review]
thanks!

**Comment by neel-ds** [comment]
> Thanks for this! Just one thing, it seems like there's a duplicate commit, would be able to sort it out locally on your branch and push only one commit? thank you

Thank you @ctrlc03! I have rebased my branch with `dev`. I reverted back to original state and pushed changes in single commit.

**Comment by ctrlc03** [comment]
> > Thanks for this! Just one thing, it seems like there's a duplicate commit, would be able to sort it out locally on your branch and push only one commit? thank you
> 
> Thank you @ctrlc03! I have rebased my branch with `dev`. I reverted back to original state and pushed changes in single commit.

thanks for doing that :)

**Review by ctrlc03 — APPROVED** [review]

**Pull request merged**
