### PR TITLE
chore: added polygon and gnosis to supported networks and benchmark

### PR DESCRIPTION
**Pull request by crisgarner**
# Description

Added Polygon, Gnosis, and their testnet to supported networks, default configs, and benchmark updates.

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://maci.pse.dev/docs/contributing) and [code of conduct](https://maci.pse.dev/docs/contributing/code-of-conduct).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Comment by crisgarner** [comment]
Squashed the commits and created a new PR for this @ctrlc03, removed the comment and pushed the benchmark for the website here

**Comment by ctrlc03** [comment]
> Squashed the commits and created a new PR for this @ctrlc03, removed the comment and pushed the benchmark for the website here

👌 thanks - please remember to use rebase not merge from now on

**Review by ctrlc03 — COMMENTED** [review]
Seems like it's not squashed there's a merge commit too

**Comment by crisgarner** [comment]
> Seems like it's not squashed there's a merge commit too

I was getting some errors on the e2e, related to the head commit and the merge from the UI kind of fixed it. Will create another branch and add the files, might be related to a merge I did few days ago to use the new script

**Comment by ctrlc03** [comment]
> > Seems like it's not squashed there's a merge commit too
> 
> I was getting some errors on the e2e, related to the head commit and the merge from the UI kind of fixed it. Will create another branch and add the files, might be related to a merge I did few days ago to use the new script

@crisgarner the exact button you used to merge dev to your branch is also a dropdown with an option to rebase. Next time you can select rebase instead and it will fix that error (for context the error means that your branch was behind dev, hence it needed a merge or rebase)

**Review by ctrlc03 — APPROVED** [review]
Thanks

**Pull request merged**
