### PR TITLE
chore(publish): fix publishing scripts to publish contracts with ceremony params

### PR DESCRIPTION
**Pull request by ctrlc03**
# Description

Add environment variable so that contracts can be built using a different state tree depth param, and thus allow for publishing to npm contracts that work with the ceremony params

## Related issue(s)

close: #973

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://github.com/privacy-scaling-explorations/maci/blob/dev/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/maci/blob/dev/CODE_OF_CONDUCT.md).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

**Comment by ctrlc03** [comment]
@yuetloo fyi

**Review by 0xmad — APPROVED** [review]
@ctrlc03 thanks!

**Comment by yuetloo** [comment]
@ctrlc03 , can you please publish a npm package with state depth 6 (for the circuit 6-8-2-3 from the ceremony)?  We only use this circuit in testing to make sure we catch any issue sooner rather than at the deployment time.

**Comment by ctrlc03** [comment]
> @ctrlc03 , can you please publish a npm package with state depth 6 (for the circuit 6-8-2-3 from the ceremony)? We only use this circuit in testing to make sure we catch any issue sooner rather than at the deployment time.

Yes, will let you know once up (once this is merged I hope https://github.com/privacy-scaling-explorations/maci/pull/989)

**Pull request merged**
